### ISSUE TITLE
Error on adding new instance - ufp_interval is no string

### ISSUE THREAD

**Issue by tomcoonen** [lociii/symcon-unifi-presence#1]
Screenshot of the error on apply, interval value is set to (default) 1.
<img width="399" alt="screen shot 2017-09-09 at 16 42 38" src="https://user-images.githubusercontent.com/988013/30241152-03082604-957e-11e7-83f6-da47dbaa636b.png">

**Comment by lociii** [comment]
Sorry, I'm discarded SymCon in favour of OpenHAB.
Will mark these projects as unmaintained. Feel free to fork and change them.
